language: php
php:
    - 5.5
    - 5.4
    - 5.3
    - 5.2
    - 5.1

install:
  - composer install

script:
 - echo $TRAVIS_PHP_VERSION
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

